import type { Config } from 'tailwindcss'

const config: Config = {
  darkMode: 'class',
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
    './lib/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        // Design System – Amanah Financial OS
        'surface':                    '#f9f9ff',
        'surface-dim':                '#cfdaf2',
        'surface-bright':             '#f9f9ff',
        'surface-container-lowest':   '#ffffff',
        'surface-container-low':      '#f0f3ff',
        'surface-container':          '#e7eeff',
        'surface-container-high':     '#dee8ff',
        'surface-container-highest':  '#d8e3fb',
        'on-surface':                 '#111c2d',
        'on-surface-variant':         '#594236',
        'inverse-surface':            '#263143',
        'inverse-on-surface':         '#ecf1ff',
        'outline':                    '#8d7164',
        'outline-variant':            '#e1c0b0',
        'surface-tint':               '#9d4400',
        'primary':                    '#9d4400',
        'on-primary':                 '#ffffff',
        'primary-container':          '#ff7200',
        'on-primary-container':       '#5a2400',
        'inverse-primary':            '#ffb690',
        'primary-fixed':              '#ffdbca',
        'primary-fixed-dim':          '#ffb690',
        'on-primary-fixed':           '#331100',
        'on-primary-fixed-variant':   '#783200',
        'secondary':                  '#006c49',
        'on-secondary':               '#ffffff',
        'secondary-container':        '#6cf8bb',
        'on-secondary-container':     '#00714d',
        'secondary-fixed':            '#6ffbbe',
        'secondary-fixed-dim':        '#4edea3',
        'on-secondary-fixed':         '#002113',
        'on-secondary-fixed-variant': '#005236',
        'tertiary':                   '#904d00',
        'on-tertiary':                '#ffffff',
        'tertiary-container':         '#e88219',
        'on-tertiary-container':      '#522900',
        'tertiary-fixed':             '#ffdcc3',
        'tertiary-fixed-dim':         '#ffb77d',
        'on-tertiary-fixed':          '#2f1500',
        'on-tertiary-fixed-variant':  '#6e3900',
        'error':                      '#ba1a1a',
        'on-error':                   '#ffffff',
        'error-container':            '#ffdad6',
        'on-error-container':         '#93000a',
        'background':                 '#f9f9ff',
        'foreground':                 '#111c2d',
        'on-background':              '#111c2d',
        'surface-variant':            '#d8e3fb',
        'border':                     '#e1c0b0',
        'input':                      '#e1c0b0',
        'ring':                       '#ff7200',
        'card': {
          DEFAULT: '#ffffff',
          foreground: '#111c2d',
        },
        'popover': {
          DEFAULT: '#ffffff',
          foreground: '#111c2d',
        },
        'muted': {
          DEFAULT: '#f0f3ff',
          foreground: '#594236',
        },
        'accent': {
          DEFAULT: '#f0f3ff',
          foreground: '#111c2d',
        },
        'destructive': {
          DEFAULT: '#ba1a1a',
          foreground: '#ffffff',
        },
      },
      borderRadius: {
        DEFAULT: '0.5rem',
        sm:      '0.25rem',
        md:      '0.75rem',
        lg:      '1rem',
        xl:      '1.5rem',
        full:    '9999px',
      },
      spacing: {
        'space-xs':       '0.25rem',
        'space-sm':       '0.5rem',
        'space-md':       '1rem',
        'space-lg':       '1.5rem',
        'space-xl':       '2rem',
        'space-2xl':      '3rem',
        'gutter':         '1.25rem',
        'gutter-dense':   '0.75rem',
        'margin':         '2rem',
        'margin-mobile':  '1rem',
        '18':             '4.5rem',  // 72px header height
        '72':             '18rem',   // 288px sidebar width
      },
      fontSize: {
        'display-lg':     ['36px', { lineHeight: '44px',  letterSpacing: '-0.02em',  fontWeight: '700' }],
        'display-sm':     ['28px', { lineHeight: '36px',  letterSpacing: '-0.015em', fontWeight: '700' }],
        'headline-lg':    ['24px', { lineHeight: '32px',  letterSpacing: '-0.01em',  fontWeight: '600' }],
        'headline-md':    ['20px', { lineHeight: '28px',  letterSpacing: '-0.01em',  fontWeight: '600' }],
        'headline-sm':    ['16px', { lineHeight: '24px',  letterSpacing: '-0.005em', fontWeight: '600' }],
        'body-lg':        ['16px', { lineHeight: '24px',  fontWeight: '400' }],
        'body-md':        ['14px', { lineHeight: '20px',  fontWeight: '400' }],
        'body-sm':        ['12px', { lineHeight: '16px',  fontWeight: '400' }],
        'metric-display': ['32px', { lineHeight: '38px',  letterSpacing: '-0.02em',  fontWeight: '700' }],
        'table-header':   ['11px', { lineHeight: '14px',  letterSpacing: '0.05em',   fontWeight: '600' }],
        'table-cell':     ['13px', { lineHeight: '18px',  fontWeight: '400' }],
        'table-cell-mono':['13px', { lineHeight: '18px',  letterSpacing: '-0.01em',  fontWeight: '500' }],
        'label-md':       ['12px', { lineHeight: '16px',  fontWeight: '500' }],
        'label-sm':       ['10px', { lineHeight: '14px',  letterSpacing: '0.03em',   fontWeight: '600' }],
      },
      fontFamily: {
        sans: ['var(--font-sans)', 'Inter', 'sans-serif'],
      },
      boxShadow: {
        'level-1': '0px 1px 3px rgba(30,41,59,0.04), 0px 4px 8px -2px rgba(255,114,0,0.03)',
        'level-2': '0px 4px 12px rgba(30,41,59,0.06), 0px 10px 24px -4px rgba(255,114,0,0.07)',
        'level-3': '0px 12px 32px -4px rgba(30,41,59,0.12), 0px 4px 12px rgba(0,0,0,0.04)',
      },
      keyframes: {
        'fade-in': {
          from: { opacity: '0' },
          to:   { opacity: '1' },
        },
        'fade-out': {
          from: { opacity: '1' },
          to:   { opacity: '0' },
        },
        'slide-in-from-bottom': {
          from: { transform: 'translateY(16px)', opacity: '0' },
          to:   { transform: 'translateY(0)', opacity: '1' },
        },
        'zoom-in-95': {
          from: { transform: 'scale(0.95)', opacity: '0' },
          to:   { transform: 'scale(1)', opacity: '1' },
        },
        'skeleton-pulse': {
          '0%, 100%': { opacity: '1' },
          '50%':       { opacity: '0.4' },
        },
      },
      animation: {
        'fade-in':              'fade-in 0.2s ease-out',
        'fade-out':             'fade-out 0.2s ease-in',
        'slide-in-from-bottom': 'slide-in-from-bottom 0.2s ease-out',
        'zoom-in-95':           'zoom-in-95 0.15s ease-out',
        'skeleton':             'skeleton-pulse 2s cubic-bezier(0.4, 0, 0.6, 1) infinite',
      },
    },
  },
  plugins: [],
}

export default config

