import {PrismaClient} from '@prisma/client';import bcrypt from 'bcryptjs';
const p=new PrismaClient();
await p.user.createMany({data:[['super','Super Admin'],['admin','Admin'],['operator','Operator']].map(([u,r])=>({username:u,name:r,role:r,passwordHash:bcrypt.hashSync(u+'123',10)}))});
const L=[['SHF','Gedung Shofiyah - TU','Administrasi/TU'],['UMR','Gedung Umar - Matham','Matham'],['CPY','Copy Center','Percetakan/copy'],['ABK','Gedung Abu Bakar',''],['KHD','Gedung Khadijah',''],['FTH','Gedung Fatimah',''],['LOB','Lobby',''],['SRP-SD','Ruang Sarpras SD','Sarpras SD'],['SRP-TK','Ruang Sarpras TK','Sarpras TK']];
await p.location.createMany({data:L.map(([code,name,description])=>({code,name,description}))});
await p.category.createMany({data:['ATK','Kebersihan','Konsumsi','Maintenance','Listrik','Air','Percetakan','Perlengkapan','Lainnya'].map(name=>({name}))});
await p.unit.createMany({data:['pcs','rim','dus','box','lusin','liter','kg','meter','pak','unit'].map(name=>({name}))});
const P=[['Kertas A4','ATK','rim',55000],['Pulpen','ATK','lusin',35000],['Map Plastik','ATK','pcs',3000],['Tinta Printer','ATK','pcs',125000],['Sabun Cuci Tangan','Kebersihan','liter',28000],['Pel Lantai','Kebersihan','pcs',45000],['Air Mineral','Konsumsi','dus',22000],['Lampu LED','Maintenance','pcs',35000],['Tinta Fotokopi','Percetakan','pcs',150000],['Stop Kontak','Perlengkapan','unit',40000]],pid={};
for(const[name,c,u,price]of P)pid[name]=(await p.product.create({data:{name,defaultPrice:price,category:{connect:{name:c}},unit:{connect:{name:u}}}})).id;
console.log('Seed selesai.');await p.$disconnect();
